name: 'corne nice_nano_v2 nice_view engrammer attempt'

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '[
         "corne_left nice_nano_v2_adapter nice_nano_v2_display",
         "corne_right nice_nano_v2_adapter nice_nano_v2_display"
      ]'
      alphas: '["engrammer"]'
      extra: '["qwerty"]'

