name: 'corne nice_nano_v2 oled engrammer'

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["corne_left nice_view_adapter nice_view", "corne_right nice_view_adapter nice_view"]'
      alphas: '["engrammer"]'
      extra: '["qwerty"]'
      kconfig: '[
        "CONFIG_ZMK_DISPLAY=y",
        "CONFIG_BT_CTLR_TX_PWR_PLUS_8=y",
        "CONFIG_ZMK_WIDGET_LAYER_STATUS=y",
        "CONFIG_ZMK_WIDGET_BATTERY_STATUS=y",
        "CONFIG_ZMK_WIDGET_BLE_STATUS=y",
        "CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y",
        "CONFIG_ZMK_WIDGET_PERIPHERAL_STATUS=y"
       ]'

