name: 'corne nice_nano oled engrammer in progress'

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano"]'
      shield: '["corne_left", "corne_right"]'
      alphas: '["engrammer"]'
      extra: '["qwerty"]'
      kconfig: '[
       "CONFIG_ZMK_DISPLAY=y",
     ]'

