name: 'corne nice_nano_v2 nice_view engrammer attempt'

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["corne_left nice_view_adapter nice_view", "corne_right nice_view_adapter nice_view"]'
      args: >-
        -DMIRYOKU_ALPHAS_ENGRAMMER
        -DMIRYOKU_EXTRA_QWERTY
        -DCONFIG_ZMK_DISPLAY=y
        -DCONFIG_ZMK_WIDGET_LAYER_STATUS=y
        -DCONFIG_ZMK_WIDGET_BATTERY_STATUS=y
        -DCONFIG_ZMK_WIDGET_BLE_STATUS=y
        -DCONFIG_ZMK_WIDGET_OUTPUT_STATUS=y
        -DCONFIG_ZMK_WIDGET_PERIPHERAL_STATUS=y

